/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 16/05/2017 20:12:44
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            16000000
#define MX_HSE_VALUE                            8000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLCLKFreq_Value                     168000000
#define MX_SYSCLKFreq_VALUE                     168000000
#define MX_HCLKFreq_Value                       168000000
#define MX_FCLKCortexFreq_Value                 168000000
#define MX_CortexFreq_Value                     168000000
#define MX_AHBFreq_Value                        168000000
#define MX_APB1Freq_Value                       42000000
#define MX_APB2Freq_Value                       84000000
#define MX_APB1TimFreq_Value                    84000000
#define MX_APB2TimFreq_Value                    168000000
#define MX_48MHZClocksFreq_Value                48000000
#define MX_EthernetFreq_Value                   168000000
#define MX_I2SClocksFreq_Value                  190000000
#define MX_RTCFreq_Value                        32000
#define MX_WatchDogFreq_Value                   32000
#define MX_MCO1PinFreq_Value                    16000000
#define MX_MCO2PinFreq_Value                    168000000

/*-------------------------------- ADC1       --------------------------------*/

#define MX_ADC1                                 1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ADCx_IN1_Pin                         PA1
#define MX_ADCx_IN1_GPIOx                       GPIOA
#define MX_ADCx_IN1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ADCx_IN1_GPIO_Pin                    GPIO_PIN_1
#define MX_ADCx_IN1_GPIO_Mode                   GPIO_MODE_ANALOG

/* DMA Configuration */

/* DMA ADC1 */
#define MX_ADC1_DMA_DMA_Handle                  
#define MX_ADC1_DMA_Instance                    DMA2_Stream0
#define MX_ADC1_DMA_FIFOMode                    DMA_FIFOMODE_DISABLE
#define MX_ADC1_DMA_Priority                    DMA_PRIORITY_LOW
#define MX_ADC1_DMA_Channel                     DMA_CHANNEL_0
#define MX_ADC1_DMA_PeriphDataAlignment         DMA_PDATAALIGN_HALFWORD
#define MX_ADC1_DMA_MemDataAlignment            DMA_MDATAALIGN_HALFWORD
#define MX_ADC1_DMA_Mode                        DMA_CIRCULAR
#define MX_ADC1_DMA_Direction                   DMA_PERIPH_TO_MEMORY
#define MX_ADC1_DMA_PeriphInc                   DMA_PINC_DISABLE
#define MX_ADC1_DMA_MemInc                      DMA_MINC_ENABLE
#define MX_ADC1_DMA_IpInstance                  

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA1_Stream6_IRQn */
#define MX_DMA1_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_0
#define MX_DMA1_Stream6_IRQn_Subriority         0

/* NVIC DMA2_Stream0_IRQn */
#define MX_DMA2_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_0
#define MX_DMA2_Stream0_IRQn_Subriority         0

/* NVIC DMA1_Stream5_IRQn */
#define MX_DMA1_Stream5_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream5_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_0
#define MX_DMA1_Stream5_IRQn_Subriority         0

/*-------------------------------- I2S3       --------------------------------*/

#define MX_I2S3                                 1

/* GPIO Configuration */

/* Pin PC11 */
#define MX_I2S3_ext_SD_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_I2S3_ext_SD_Pin                      PC11
#define MX_I2S3_ext_SD_GPIOx                    GPIOC
#define MX_I2S3_ext_SD_GPIO_PuPd                GPIO_NOPULL
#define MX_I2S3_ext_SD_GPIO_Pin                 GPIO_PIN_11
#define MX_I2S3_ext_SD_GPIO_AF                  GPIO_AF5_I2S3ext
#define MX_I2S3_ext_SD_GPIO_Mode                GPIO_MODE_AF_PP

/* Pin PA4 */
#define MX_I2S3_WS_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_I2S3_WS_Pin                          PA4
#define MX_I2S3_WS_GPIOx                        GPIOA
#define MX_I2S3_WS_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S3_WS_[CS43L22_LRCK]               I2S3_WS
#define MX_I2S3_WS_GPIO_Pin                     GPIO_PIN_4
#define MX_I2S3_WS_GPIO_AF                      GPIO_AF6_SPI3
#define MX_I2S3_WS_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC12 */
#define MX_I2S3_SD_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_I2S3_SD_Pin                          PC12
#define MX_I2S3_SD_GPIOx                        GPIOC
#define MX_I2S3_SD_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S3_SD_[CS43L22_SDIN]               I2S3_SD
#define MX_I2S3_SD_GPIO_Pin                     GPIO_PIN_12
#define MX_I2S3_SD_GPIO_AF                      GPIO_AF6_SPI3
#define MX_I2S3_SD_GPIO_Mode                    GPIO_MODE_AF_PP

/* Pin PC7 */
#define MX_I2S3_MCK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2S3_MCK_Pin                         PC7
#define MX_I2S3_MCK_GPIOx                       GPIOC
#define MX_I2S3_MCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_I2S3_MCK_[CS43L22_MCLK]              I2S3_MCK
#define MX_I2S3_MCK_GPIO_Pin                    GPIO_PIN_7
#define MX_I2S3_MCK_GPIO_AF                     GPIO_AF6_SPI3
#define MX_I2S3_MCK_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC10 */
#define MX_I2S3_CK_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_I2S3_CK_Pin                          PC10
#define MX_I2S3_CK_GPIOx                        GPIOC
#define MX_I2S3_CK_GPIO_PuPd                    GPIO_NOPULL
#define MX_I2S3_SCK_[CS43L22_SCLK]              I2S3_CK
#define MX_I2S3_CK_GPIO_Pin                     GPIO_PIN_10
#define MX_I2S3_CK_GPIO_AF                      GPIO_AF6_SPI3
#define MX_I2S3_CK_GPIO_Mode                    GPIO_MODE_AF_PP

/* NVIC Configuration */

/* NVIC SPI3_IRQn */
#define MX_SPI3_IRQn_interruptPremptionPriority 0
#define MX_SPI3_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_0
#define MX_SPI3_IRQn_Subriority                 0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/* Pin PA13 */
#define MX_SYS_JTMS-SWDIO_Pin                   PA13
#define MX_SWDIO                                SYS_JTMS-SWDIO

/* Pin PA14 */
#define MX_SYS_JTCK-SWCLK_Pin                   PA14
#define MX_SWCLK                                SYS_JTCK-SWCLK

/* Pin PB3 */
#define MX_SYS_JTDO-SWO_Pin                     PB3
#define MX_SWO                                  SYS_JTDO-SWO

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* Pin PB7 */
#define MX_S_TIM4_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH2_Pin                       PB7
#define MX_S_TIM4_CH2_GPIOx                     GPIOB
#define MX_S_TIM4_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH2_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM4_CH2_GPIO_AF                   GPIO_AF2_TIM4

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PA2 */
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_TX_Pin                        PA2
#define MX_USART2_TX_GPIOx                      GPIOA
#define MX_USART2_TX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_2
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_TX_GPIO_Mode                  GPIO_MODE_AF_PP

/* Pin PA3 */
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_VERY_HIGH
#define MX_USART2_RX_Pin                        PA3
#define MX_USART2_RX_GPIOx                      GPIOA
#define MX_USART2_RX_GPIO_PuPd                  GPIO_PULLUP
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_3
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_RX_GPIO_Mode                  GPIO_MODE_AF_PP

/* DMA Configuration */

/* DMA USART2_TX */
#define MX_USART2_TX_DMA_DMA_Handle             
#define MX_USART2_TX_DMA_Instance               DMA1_Stream6
#define MX_USART2_TX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART2_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART2_TX_DMA_Channel                DMA_CHANNEL_4
#define MX_USART2_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_HALFWORD
#define MX_USART2_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_HALFWORD
#define MX_USART2_TX_DMA_Mode                   DMA_CIRCULAR
#define MX_USART2_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART2_TX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_USART2_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART2_TX_DMA_IpInstance             

/* DMA USART2_RX */
#define MX_USART2_RX_DMA_DMA_Handle             
#define MX_USART2_RX_DMA_Instance               DMA1_Stream5
#define MX_USART2_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART2_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART2_RX_DMA_Channel                DMA_CHANNEL_4
#define MX_USART2_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_HALFWORD
#define MX_USART2_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_HALFWORD
#define MX_USART2_RX_DMA_Mode                   DMA_CIRCULAR
#define MX_USART2_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART2_RX_DMA_PeriphInc              DMA_PINC_DISABLE
#define MX_USART2_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART2_RX_DMA_IpInstance             

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PD12 */
#define MX_PD12_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD12_Pin                             PD12
#define MX_PD12_GPIOx                           GPIOD
#define MX_PD12_PinState                        GPIO_PIN_RESET
#define MX_PD12_GPIO_PuPd                       GPIO_NOPULL
#define MX_LD4_[Green_Led]                      PD12
#define MX_PD12_GPIO_Pin                        GPIO_PIN_12
#define MX_PD12_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PD5 */
#define MX_PD5_Pin                              PD5
#define MX_PD5_GPIOx                            GPIOD
#define MX_PD5_GPIO_PuPd                        GPIO_NOPULL
#define MX_OTG_FS_OverCurrent                   PD5
#define MX_PD5_GPIO_Pin                         GPIO_PIN_5
#define MX_PD5_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PB2 */
#define MX_PB2_Pin                              PB2
#define MX_PB2_GPIOx                            GPIOB
#define MX_PB2_GPIO_PuPd                        GPIO_NOPULL
#define MX_BOOT1                                PB2
#define MX_PB2_GPIO_Pin                         GPIO_PIN_2
#define MX_PB2_GPIO_Mode                        GPIO_MODE_INPUT

/* Pin PD4 */
#define MX_PD4_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PD4_Pin                              PD4
#define MX_PD4_GPIOx                            GPIOD
#define MX_PD4_PinState                         GPIO_PIN_RESET
#define MX_PD4_GPIO_PuPd                        GPIO_NOPULL
#define MX_Audio_RST_[CS43L22_RESET]            PD4
#define MX_PD4_GPIO_Pin                         GPIO_PIN_4
#define MX_PD4_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD14 */
#define MX_PD14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD14_Pin                             PD14
#define MX_PD14_GPIOx                           GPIOD
#define MX_PD14_PinState                        GPIO_PIN_RESET
#define MX_PD14_GPIO_PuPd                       GPIO_NOPULL
#define MX_LD5_[Red_Led]                        PD14
#define MX_PD14_GPIO_Pin                        GPIO_PIN_14
#define MX_PD14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PA0-WKUP */
#define MX_PA0_WKUP_Pin                         PA0_WKUP
#define MX_PA0_WKUP_GPIOx                       GPIOA
#define MX_PA0_WKUP_GPIO_PuPd                   GPIO_NOPULL
#define MX_B1_[Blue_PushButton]                 PA0_WKUP
#define MX_PA0_WKUP_GPIO_Pin                    GPIO_PIN_0
#define MX_PA0_WKUP_GPIO_ModeDefaultEXTI        GPIO_MODE_EVT_RISING

/* Pin PD13 */
#define MX_PD13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD13_Pin                             PD13
#define MX_PD13_GPIOx                           GPIOD
#define MX_PD13_PinState                        GPIO_PIN_RESET
#define MX_PD13_GPIO_PuPd                       GPIO_NOPULL
#define MX_LD3_[Orange_Led]                     PD13
#define MX_PD13_GPIO_Pin                        GPIO_PIN_13
#define MX_PD13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PC0 */
#define MX_PC0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PC0_Pin                              PC0
#define MX_PC0_GPIOx                            GPIOC
#define MX_PC0_PinState                         GPIO_PIN_SET
#define MX_PC0_GPIO_PuPd                        GPIO_NOPULL
#define MX_OTG_FS_PowerSwitchOn                 PC0
#define MX_PC0_GPIO_Pin                         GPIO_PIN_0
#define MX_PC0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PD15 */
#define MX_PD15_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PD15_Pin                             PD15
#define MX_PD15_GPIOx                           GPIOD
#define MX_PD15_PinState                        GPIO_PIN_RESET
#define MX_PD15_GPIO_PuPd                       GPIO_NOPULL
#define MX_LD6_[Blue_Led]                       PD15
#define MX_PD15_GPIO_Pin                        GPIO_PIN_15
#define MX_PD15_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE1 */
#define MX_PE1_Pin                              PE1
#define MX_PE1_GPIOx                            GPIOE
#define MX_PE1_GPIO_PuPd                        GPIO_NOPULL
#define MX_MEMS_INT2_[LIS302DL_INT2]            PE1
#define MX_PE1_GPIO_Pin                         GPIO_PIN_1
#define MX_PE1_GPIO_ModeDefaultEXTI             GPIO_MODE_EVT_RISING

/* Pin PE3 */
#define MX_PE3_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE3_Pin                              PE3
#define MX_PE3_GPIOx                            GPIOE
#define MX_PE3_PinState                         GPIO_PIN_RESET
#define MX_PE3_GPIO_PuPd                        GPIO_NOPULL
#define MX_CS_I2C_SPI_[LIS302DL_CS_I2C_SPI]     PE3
#define MX_PE3_GPIO_Pin                         GPIO_PIN_3
#define MX_PE3_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

